version: '3'

services:
  app:
    build: .
    command: jekyll serve --config _config.yml,_config_development.yml 
    volumes:
      - .:/srv/jekyll
      - gem_cache:/usr/gem
    ports:
      - "8080:8080"
      - "3000:3000"
      - "3001:3001"

volumes:
  gem_cache:
